apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: influxdb
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template: #under this line is pod template
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: my-influxdb
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
          name: influxdb
        volumeMounts:
        - name: influxdb-persistent-storage
          mountPath: /var/lib/influxdb
      volumes:
      - name: influxdb-persistent-storage
        persistentVolumeClaim:
          claimName: influxdb-pv-claim
---

apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  ports:
    - name: influxdb
      port: 8086
      targetPort: 8086
  selector:
    app: influxdb
  clusterIP: None
