apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: my-mysql
        imagePullPolicy: Never
        name: mysql
        livenessProbe:
          exec:
            command: ["sh", "tmp/liveness.sh"]
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 30
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: root
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /app
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim


---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports: 
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
