apiVersion: apps/v1 #version of API
kind: Deployment #type of resorce
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector: #which pod you start.
    matchLabels:
      app: nginx
  template: #under this line is pod template
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: my-nginx
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command: ["sh", "tmp/liveness.sh"]
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 30
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: "ft_service"
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
