apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: phpmyadmin
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - image: my-phpadmin
        imagePullPolicy: Never
        name: pypmyadmin
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: "ft_service"
spec:
  type: LoadBalancer
  selector:
    app: pypmyadmin
  ports:
    - name: pypmyadmin
      port: 5000
