apiVersion: apps/v1 
kind: Deployment
metadata:
  labels:
    app: wordpress
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template: 
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: my-wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: "ft_service"
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
    - name: wodpress
      port: 5050
      targetPort: 5050
      protocol: TCP
