apiVersion: apps/v1 
kind: Deployment
metadata:
  labels:
    app: ftps
  name: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: my-ftps
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command: ["sh", "/liveness.sh"]
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 30
        ports:
        - containerPort: 20
          name: ftps-datapath
        - containerPort: 21
          name: ftps
        - containerPort: 60000
          name: pasv
        volumeMounts:
        - name: ftps-persistent-storage
          mountPath: /home
      volumes:
      - name: ftps-persistent-storage
        persistentVolumeClaim:
          claimName: ftps-pv-claim

---

apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: "ft_service"
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
    - name: ftps-datapath
      port: 20
      targetPort: 20
    - name: ftps
      port: 21
      targetPort: 21
    - name: pasv
      port: 60000
      targetPort: 60000
